In [1]:
# load library
import numpy as np


"""
Problem: Create a Matrix
"""

# the matrix
matrix = np.array([[1,2],
                  [1,2],
                  [1,2]])

print(matrix.shape) # (3 rows, 2 columns)
print(f"The matrix size is {matrix.size}")

(3, 2)
The matrix size is 6


In [2]:
# load library
import numpy as np
from scipy import sparse

"""
Problem:

Given data with very few nonzero values, you want to efficiently represent it.

"""

# Matrix
matrix = np.array([[0, 0],
                  [0,1],
                  [3,0]])

# Compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

# View sparse matrix
print(matrix_sparse)

# Create Larger Matrix
large_matrix = ([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                 [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# Create compressed sparse row (CSR) matrix
large_matrix_sparse = sparse.csr_matrix(large_matrix)

# View original sparse matrix
print(f"\n{matrix_sparse}")

# View larger sparse matrix
print(f"\n{large_matrix_sparse}")

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 10)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


#### Selecting Elements 😼 in Vector or Matrix

In [3]:
# Load library
import numpy as np

# Row vector
vector = np.array([1, 2 , 3, 4, 5, 6])

# Create matrix
matrix1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Select third element of vector
vector[2] # 3

# Select second row, second column
matrix1[1, 1] # 5


5

In [4]:
# Select all elements of a vector
vector[:]

array([1, 2, 3, 4, 5, 6])

In [5]:
# Select everything up to and including the third element
vector[:3]

array([1, 2, 3])

In [6]:
# Select everything after the third element
vector[3:]

array([4, 5, 6])

In [7]:
# Select the last element
vector[-1]

6

In [8]:
# Select the first two rows and all columns of a matrix
matrix1[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
# Select all rows and the second column
matrix1[:,1:2]

array([[2],
       [5],
       [8]])

#### Finding the maximum and minimun values 👀

In [14]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Return maximum value
np.max(matrix)


9

In [15]:
# Return minimum value
np.min(matrix)

1

In [16]:
# Find maximum value in each col
np.max(matrix, axis=0)

array([7, 8, 9])

In [17]:
# Find maximum elements in each row
np.max(matrix, axis=1)

array([3, 6, 9])

#### Calculating the Average, Variance, and Standard Deviation

In [2]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Return mean
np.mean(matrix)

5.0

In [3]:
# Return variance
np.var(matrix)


6.666666666666667

In [4]:
# Return standard variation
np.std(matrix)

2.581988897471611